# Generated by Django 2.1.2 on 2018-10-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('trabajo', models.CharField(blank=True, max_length=100)),
                ('foto', models.URLField(blank=True, max_length=400)),
                ('prioridad', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='charla',
            name='ponentes',
            field=models.ManyToManyField(to='charlas.Ponente'),
        ),
    ]
